version: '3.8'

services:
  # Backend Simple HTTP Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pi-monitor-backend
    restart: unless-stopped
    networks:
      - pi-monitor-network
    expose:
      - "5001"  # Expose port internally only
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
      - PORT=5001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./logs:/app/logs
      - /var/log:/host/var/log:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  # Frontend React Application with Apache
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pi-monitor-frontend
    restart: unless-stopped
    networks:
      - pi-monitor-network
    expose:
      - "80"  # Expose port internally only
    environment:
      - REACT_APP_SERVER_URL=https://pi.cabhinav.com
      - REACT_APP_API_BASE_URL=https://pi.cabhinav.com
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./frontend-logs:/var/log/apache2

  # Nginx Reverse Proxy for Domain
  nginx:
    image: nginx:alpine
    container_name: pi-monitor-nginx
    restart: unless-stopped
    networks:
      - pi-monitor-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-pi-subdomain.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  pi-monitor-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  logs:
  frontend-logs:
  nginx-logs:
