version: '3.8'

services:
  # Backend Simple HTTP Server
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: pi-monitor-backend
    restart: unless-stopped
    network_mode: host
    environment:
      - PORT=5001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Frontend React Application with Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pi-monitor-frontend
    restart: unless-stopped
    network_mode: host
    environment:
      - REACT_APP_SERVER_URL=dynamic
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes: {}
