version: '3.8'

services:
  # Backend Simple HTTP Server (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pi-monitor-backend-dev
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - pi-monitor-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Frontend React Application (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pi-monitor-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_URL=http://localhost:5001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - pi-monitor-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  pi-monitor-network:
    driver: bridge

volumes: {}
