version: '3.8'

services:
  # Frontend React Application with Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pi-monitor-frontend
    restart: unless-stopped
    network_mode: host
    environment:
      - REACT_APP_SERVER_URL=dynamic
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes: {}
