name: Deploy Frontend to GH Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

concurrency:
  group: gh-pages
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          cp build/index.html build/404.html
        env:
          REACT_APP_SERVER_URL: https://pi.cabhinav.com
          REACT_APP_API_BASE_URL: https://pi.cabhinav.com
          REACT_APP_ENVIRONMENT: production

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/build
          force_orphan: true


